name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y cmake
          mkdir build && cmake -B build -S . && cmake --build build
          ./build/main 2 2