name: build and run
on: [push]
jobs:
  build and run:
    runs-on: ubuntu-latest
    stages:
      - uses: actions/checkout@v4
      - run: g++ main.cpp square.h square.cpp -o main
      - run: ./main.cpp 3 2